version: '3'

services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: "my_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_ROOT_PASSWORD: "super-secret"
    ports:
      - "5432:5432"
    volumes:
      - /mnt/db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.db == true

networks:
  backend:
    external: true
