version: '3'

services:
  agent:
    image: portainer/agent:2.16.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.16.1
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - '9000:9000'
      - '9443:9443'
      - '8000:8000'
    volumes:
      - /mnt/portainer:/data
    networks:
      - portainer
    deploy:
      mode: replicated
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  portainer:
    external: true
